# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\JESD\mw.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(912, 442)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(912, 442))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cw = QtWidgets.QWidget(self.centralwidget)
        self.cw.setGeometry(QtCore.QRect(10, 10, 891, 391))
        self.cw.setMinimumSize(QtCore.QSize(891, 391))
        self.cw.setMaximumSize(QtCore.QSize(891, 391))
        self.cw.setObjectName("cw")
        self.gridLayout = QtWidgets.QGridLayout(self.cw)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.cw)
        self.groupBox_2.setObjectName("groupBox_2")
        self.logTextEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.logTextEdit.setGeometry(QtCore.QRect(10, 20, 681, 131))
        self.logTextEdit.setObjectName("logTextEdit")
        self.clearLogPushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.clearLogPushButton.setGeometry(QtCore.QRect(750, 60, 81, 31))
        self.clearLogPushButton.setObjectName("clearLogPushButton")
        self.gridLayout.addWidget(self.groupBox_2, 2, 0, 1, 2)
        self.tabWidget = QtWidgets.QTabWidget(self.cw)
        self.tabWidget.setMaximumSize(QtCore.QSize(400, 200))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 111, 16))
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 381, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.fileLineEdit.setObjectName("fileLineEdit")
        self.horizontalLayout.addWidget(self.fileLineEdit)
        self.selectFilePushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.selectFilePushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.selectFilePushButton.setObjectName("selectFilePushButton")
        self.horizontalLayout.addWidget(self.selectFilePushButton)
        self.writeFilePushButton = QtWidgets.QPushButton(self.tab)
        self.writeFilePushButton.setEnabled(False)
        self.writeFilePushButton.setGeometry(QtCore.QRect(280, 120, 91, 21))
        self.writeFilePushButton.setObjectName("writeFilePushButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 10, 242, 48))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.regAddrLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.regAddrLineEdit.setObjectName("regAddrLineEdit")
        self.gridLayout_2.addWidget(self.regAddrLineEdit, 0, 1, 1, 1)
        self.regValLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.regValLineEdit.setObjectName("regValLineEdit")
        self.gridLayout_2.addWidget(self.regValLineEdit, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 2, 1, 1)
        self.regReadPushButton = QtWidgets.QPushButton(self.tab_2)
        self.regReadPushButton.setEnabled(False)
        self.regReadPushButton.setGeometry(QtCore.QRect(220, 110, 75, 23))
        self.regReadPushButton.setObjectName("regReadPushButton")
        self.regWritePushButton = QtWidgets.QPushButton(self.tab_2)
        self.regWritePushButton.setEnabled(False)
        self.regWritePushButton.setGeometry(QtCore.QRect(310, 110, 75, 23))
        self.regWritePushButton.setObjectName("regWritePushButton")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.cw)
        self.groupBox_4.setMaximumSize(QtCore.QSize(460, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.LEDDevPushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.LEDDevPushButton.setEnabled(False)
        self.LEDDevPushButton.setGeometry(QtCore.QRect(300, 150, 141, 31))
        self.LEDDevPushButton.setObjectName("LEDDevPushButton")
        self.widget = QtWidgets.QWidget(self.groupBox_4)
        self.widget.setGeometry(QtCore.QRect(10, 20, 411, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.devListComboBox = QtWidgets.QComboBox(self.widget)
        self.devListComboBox.setObjectName("devListComboBox")
        self.horizontalLayout_2.addWidget(self.devListComboBox)
        self.refrDevListPushButton = QtWidgets.QPushButton(self.widget)
        self.refrDevListPushButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.refrDevListPushButton.setObjectName("refrDevListPushButton")
        self.horizontalLayout_2.addWidget(self.refrDevListPushButton)
        self.widget1 = QtWidgets.QWidget(self.groupBox_4)
        self.widget1.setGeometry(QtCore.QRect(100, 80, 201, 51))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.connectDevPushButton = QtWidgets.QPushButton(self.widget1)
        self.connectDevPushButton.setObjectName("connectDevPushButton")
        self.horizontalLayout_3.addWidget(self.connectDevPushButton)
        self.disconnectDevPushButton = QtWidgets.QPushButton(self.widget1)
        self.disconnectDevPushButton.setEnabled(False)
        self.disconnectDevPushButton.setObjectName("disconnectDevPushButton")
        self.horizontalLayout_3.addWidget(self.disconnectDevPushButton)
        self.widget2 = QtWidgets.QWidget(self.groupBox_4)
        self.widget2.setGeometry(QtCore.QRect(10, 140, 271, 51))
        self.widget2.setObjectName("widget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.widget2)
        self.label_7.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 2, 1)
        self.pll1Label = QtWidgets.QLabel(self.widget2)
        self.pll1Label.setObjectName("pll1Label")
        self.gridLayout_3.addWidget(self.pll1Label, 0, 1, 2, 1)
        self.readPllPushButton = QtWidgets.QPushButton(self.widget2)
        self.readPllPushButton.setEnabled(False)
        self.readPllPushButton.setMaximumSize(QtCore.QSize(65, 16777215))
        self.readPllPushButton.setObjectName("readPllPushButton")
        self.gridLayout_3.addWidget(self.readPllPushButton, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget2)
        self.label_8.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.pll2Label = QtWidgets.QLabel(self.widget2)
        self.pll2Label.setObjectName("pll2Label")
        self.gridLayout_3.addWidget(self.pll2Label, 2, 1, 1, 1)
        self.clearPllPushButton = QtWidgets.QPushButton(self.widget2)
        self.clearPllPushButton.setEnabled(False)
        self.clearPllPushButton.setMaximumSize(QtCore.QSize(65, 16777215))
        self.clearPllPushButton.setObjectName("clearPllPushButton")
        self.gridLayout_3.addWidget(self.clearPllPushButton, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 912, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JESD_8SYNCV01"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Лог"))
        self.clearLogPushButton.setText(_translate("MainWindow", "Очистить"))
        self.label_3.setText(_translate("MainWindow", "Путь к файлу:"))
        self.fileLineEdit.setText(_translate("MainWindow", "H:/JESD/doc/fmc4R_clin2_100_to_2K5_pdf25cp16_jmode5_lvpecl20.txt"))
        self.selectFilePushButton.setText(_translate("MainWindow", "..."))
        self.writeFilePushButton.setText(_translate("MainWindow", "Запись!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Запись в файл"))
        self.label.setText(_translate("MainWindow", "Адрес регистра:"))
        self.regAddrLineEdit.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "Значение регистра:"))
        self.label_4.setText(_translate("MainWindow", "HEX"))
        self.label_5.setText(_translate("MainWindow", "HEX"))
        self.regReadPushButton.setText(_translate("MainWindow", "Считать"))
        self.regWritePushButton.setText(_translate("MainWindow", "Записать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Ручное чтение и запись"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Выбор устройства"))
        self.LEDDevPushButton.setText(_translate("MainWindow", "Мигнуть светодиодом"))
        self.label_6.setText(_translate("MainWindow", "Список JESD:"))
        self.refrDevListPushButton.setText(_translate("MainWindow", "Обновить"))
        self.connectDevPushButton.setText(_translate("MainWindow", "Подключиться"))
        self.disconnectDevPushButton.setText(_translate("MainWindow", "Отключиться"))
        self.label_7.setText(_translate("MainWindow", "PLL1 Status:"))
        self.pll1Label.setText(_translate("MainWindow", "-"))
        self.readPllPushButton.setText(_translate("MainWindow", "Проверить"))
        self.label_8.setText(_translate("MainWindow", "PLL2 Status:"))
        self.pll2Label.setText(_translate("MainWindow", "-"))
        self.clearPllPushButton.setText(_translate("MainWindow", "Очистить"))


