# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\JESD\mw.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(740, 450)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(740, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cw = QtWidgets.QWidget(self.centralwidget)
        self.cw.setGeometry(QtCore.QRect(10, 10, 740, 410))
        self.cw.setMinimumSize(QtCore.QSize(740, 410))
        self.cw.setMaximumSize(QtCore.QSize(740, 410))
        self.cw.setObjectName("cw")
        self.layoutWidget = QtWidgets.QWidget(self.cw)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 9, 711, 391))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(390, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(390, 130))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 371, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setMinimumSize(QtCore.QSize(115, 0))
        self.label_6.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.devListComboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.devListComboBox.setObjectName("devListComboBox")
        self.horizontalLayout_2.addWidget(self.devListComboBox)
        self.refrDevListPushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.refrDevListPushButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.refrDevListPushButton.setObjectName("refrDevListPushButton")
        self.horizontalLayout_2.addWidget(self.refrDevListPushButton)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 70, 111, 51))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.connectDevPushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.connectDevPushButton.setObjectName("connectDevPushButton")
        self.horizontalLayout_3.addWidget(self.connectDevPushButton)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(240, 70, 123, 54))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LEDDevPushButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.LEDDevPushButton.setEnabled(False)
        self.LEDDevPushButton.setObjectName("LEDDevPushButton")
        self.verticalLayout.addWidget(self.LEDDevPushButton)
        self.resetPushButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.resetPushButton.setEnabled(False)
        self.resetPushButton.setObjectName("resetPushButton")
        self.verticalLayout.addWidget(self.resetPushButton)
        self.gridLayout.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(280, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(280, 130))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 111, 16))
        self.label_3.setObjectName("label_3")
        self.layoutWidget4 = QtWidgets.QWidget(self.tab)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 30, 201, 31))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileLineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.fileLineEdit.setText("")
        self.fileLineEdit.setObjectName("fileLineEdit")
        self.horizontalLayout.addWidget(self.fileLineEdit)
        self.selectFilePushButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.selectFilePushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.selectFilePushButton.setObjectName("selectFilePushButton")
        self.horizontalLayout.addWidget(self.selectFilePushButton)
        self.writeFilePushButton = QtWidgets.QPushButton(self.tab)
        self.writeFilePushButton.setEnabled(False)
        self.writeFilePushButton.setGeometry(QtCore.QRect(130, 70, 91, 21))
        self.writeFilePushButton.setObjectName("writeFilePushButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget5 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 10, 242, 48))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget5)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.regAddrLineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        self.regAddrLineEdit.setText("")
        self.regAddrLineEdit.setObjectName("regAddrLineEdit")
        self.gridLayout_2.addWidget(self.regAddrLineEdit, 0, 1, 1, 1)
        self.regValLineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        self.regValLineEdit.setObjectName("regValLineEdit")
        self.gridLayout_2.addWidget(self.regValLineEdit, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 2, 1, 1)
        self.regReadPushButton = QtWidgets.QPushButton(self.tab_2)
        self.regReadPushButton.setEnabled(False)
        self.regReadPushButton.setGeometry(QtCore.QRect(100, 70, 75, 23))
        self.regReadPushButton.setObjectName("regReadPushButton")
        self.regWritePushButton = QtWidgets.QPushButton(self.tab_2)
        self.regWritePushButton.setEnabled(False)
        self.regWritePushButton.setGeometry(QtCore.QRect(180, 70, 75, 23))
        self.regWritePushButton.setObjectName("regWritePushButton")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(680, 230))
        self.groupBox_2.setMaximumSize(QtCore.QSize(680, 230))
        self.groupBox_2.setObjectName("groupBox_2")
        self.logTextEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.logTextEdit.setGeometry(QtCore.QRect(10, 20, 661, 131))
        self.logTextEdit.setObjectName("logTextEdit")
        self.clearLogPushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.clearLogPushButton.setGeometry(QtCore.QRect(590, 160, 81, 31))
        self.clearLogPushButton.setObjectName("clearLogPushButton")
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget6.setGeometry(QtCore.QRect(20, 160, 405, 61))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_7.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 2, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_8.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.readPllPushButton = QtWidgets.QPushButton(self.layoutWidget6)
        self.readPllPushButton.setEnabled(False)
        self.readPllPushButton.setMaximumSize(QtCore.QSize(65, 16777215))
        self.readPllPushButton.setObjectName("readPllPushButton")
        self.gridLayout_3.addWidget(self.readPllPushButton, 0, 2, 1, 1)
        self.pll1Label = QtWidgets.QLabel(self.layoutWidget6)
        self.pll1Label.setMinimumSize(QtCore.QSize(100, 0))
        self.pll1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.pll1Label.setObjectName("pll1Label")
        self.gridLayout_3.addWidget(self.pll1Label, 0, 1, 2, 1)
        self.pll2Label = QtWidgets.QLabel(self.layoutWidget6)
        self.pll2Label.setMinimumSize(QtCore.QSize(100, 0))
        self.pll2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.pll2Label.setObjectName("pll2Label")
        self.gridLayout_3.addWidget(self.pll2Label, 2, 1, 1, 1)
        self.clearPllPushButton = QtWidgets.QPushButton(self.layoutWidget6)
        self.clearPllPushButton.setEnabled(False)
        self.clearPllPushButton.setMaximumSize(QtCore.QSize(65, 16777215))
        self.clearPllPushButton.setObjectName("clearPllPushButton")
        self.gridLayout_3.addWidget(self.clearPllPushButton, 2, 2, 1, 1)
        self.autoStatCheckBox = QtWidgets.QCheckBox(self.layoutWidget6)
        self.autoStatCheckBox.setEnabled(False)
        self.autoStatCheckBox.setMinimumSize(QtCore.QSize(160, 0))
        self.autoStatCheckBox.setObjectName("autoStatCheckBox")
        self.gridLayout_3.addWidget(self.autoStatCheckBox, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 740, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JESD_8SYNCV01"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Выбор устройства"))
        self.label_6.setText(_translate("MainWindow", "Список устройств:"))
        self.refrDevListPushButton.setText(_translate("MainWindow", "Обновить"))
        self.connectDevPushButton.setText(_translate("MainWindow", "Подключиться"))
        self.LEDDevPushButton.setText(_translate("MainWindow", "Мигнуть светодиодом"))
        self.resetPushButton.setText(_translate("MainWindow", "Сброс LMK"))
        self.label_3.setText(_translate("MainWindow", "Путь к файлу:"))
        self.selectFilePushButton.setText(_translate("MainWindow", "..."))
        self.writeFilePushButton.setText(_translate("MainWindow", "Запись!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Запись из файла"))
        self.label.setText(_translate("MainWindow", "Адрес регистра:"))
        self.label_2.setText(_translate("MainWindow", "Значение регистра:"))
        self.label_4.setText(_translate("MainWindow", "HEX"))
        self.label_5.setText(_translate("MainWindow", "HEX"))
        self.regReadPushButton.setText(_translate("MainWindow", "Считать"))
        self.regWritePushButton.setText(_translate("MainWindow", "Записать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Ручное чтение и запись"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Лог"))
        self.clearLogPushButton.setText(_translate("MainWindow", "Очистить"))
        self.label_7.setText(_translate("MainWindow", "PLL1 Status:"))
        self.label_8.setText(_translate("MainWindow", "PLL2 Status:"))
        self.readPllPushButton.setText(_translate("MainWindow", "Проверить"))
        self.pll1Label.setText(_translate("MainWindow", "-"))
        self.pll2Label.setText(_translate("MainWindow", "-"))
        self.clearPllPushButton.setText(_translate("MainWindow", "Очистить"))
        self.autoStatCheckBox.setText(_translate("MainWindow", "Автообновление статуса"))


