# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\JESD\mw.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 500)
        MainWindow.setMinimumSize(QtCore.QSize(650, 500))
        MainWindow.setMaximumSize(QtCore.QSize(650, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cw = QtWidgets.QWidget(self.centralwidget)
        self.cw.setGeometry(QtCore.QRect(20, 10, 630, 470))
        self.cw.setMinimumSize(QtCore.QSize(630, 470))
        self.cw.setMaximumSize(QtCore.QSize(630, 470))
        self.cw.setObjectName("cw")
        self.logTextEdit = QtWidgets.QTextEdit(self.cw)
        self.logTextEdit.setGeometry(QtCore.QRect(10, 10, 591, 221))
        self.logTextEdit.setReadOnly(True)
        self.logTextEdit.setObjectName("logTextEdit")
        self.clearLogPushButton = QtWidgets.QPushButton(self.cw)
        self.clearLogPushButton.setGeometry(QtCore.QRect(521, 244, 77, 23))
        self.clearLogPushButton.setObjectName("clearLogPushButton")
        self.autoStatCheckBox = QtWidgets.QCheckBox(self.cw)
        self.autoStatCheckBox.setEnabled(True)
        self.autoStatCheckBox.setGeometry(QtCore.QRect(60, 290, 160, 21))
        self.autoStatCheckBox.setMinimumSize(QtCore.QSize(160, 0))
        self.autoStatCheckBox.setObjectName("autoStatCheckBox")
        self.toolBox = QtWidgets.QToolBox(self.cw)
        self.toolBox.setGeometry(QtCore.QRect(0, 340, 611, 111))
        self.toolBox.setObjectName("toolBox")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 611, 57))
        self.page_3.setObjectName("page_3")
        self.widget = QtWidgets.QWidget(self.page_3)
        self.widget.setGeometry(QtCore.QRect(10, 0, 591, 51))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileLineEdit = QtWidgets.QLineEdit(self.widget)
        self.fileLineEdit.setText("")
        self.fileLineEdit.setObjectName("fileLineEdit")
        self.horizontalLayout.addWidget(self.fileLineEdit)
        self.selectFilePushButton = QtWidgets.QPushButton(self.widget)
        self.selectFilePushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.selectFilePushButton.setObjectName("selectFilePushButton")
        self.horizontalLayout.addWidget(self.selectFilePushButton)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.writeFilePushButton = QtWidgets.QPushButton(self.widget)
        self.writeFilePushButton.setEnabled(True)
        self.writeFilePushButton.setObjectName("writeFilePushButton")
        self.horizontalLayout_4.addWidget(self.writeFilePushButton)
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 611, 57))
        self.page_4.setObjectName("page_4")
        self.layoutWidget = QtWidgets.QWidget(self.page_4)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 0, 242, 48))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.regAddrLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.regAddrLineEdit.setText("")
        self.regAddrLineEdit.setObjectName("regAddrLineEdit")
        self.gridLayout_2.addWidget(self.regAddrLineEdit, 0, 1, 1, 1)
        self.regValLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.regValLineEdit.setObjectName("regValLineEdit")
        self.gridLayout_2.addWidget(self.regValLineEdit, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 2, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.page_4)
        self.widget1.setGeometry(QtCore.QRect(430, 0, 77, 54))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.regReadPushButton = QtWidgets.QPushButton(self.widget1)
        self.regReadPushButton.setEnabled(True)
        self.regReadPushButton.setObjectName("regReadPushButton")
        self.verticalLayout_2.addWidget(self.regReadPushButton)
        self.regWritePushButton = QtWidgets.QPushButton(self.widget1)
        self.regWritePushButton.setEnabled(True)
        self.regWritePushButton.setObjectName("regWritePushButton")
        self.verticalLayout_2.addWidget(self.regWritePushButton)
        self.toolBox.addItem(self.page_4, "")
        self.layoutWidget1 = QtWidgets.QWidget(self.cw)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 250, 350, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.pll1Label = QtWidgets.QLabel(self.layoutWidget1)
        self.pll1Label.setMinimumSize(QtCore.QSize(100, 0))
        self.pll1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.pll1Label.setObjectName("pll1Label")
        self.horizontalLayout_2.addWidget(self.pll1Label)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.pll2Label = QtWidgets.QLabel(self.layoutWidget1)
        self.pll2Label.setMinimumSize(QtCore.QSize(100, 0))
        self.pll2Label.setAlignment(QtCore.Qt.AlignCenter)
        self.pll2Label.setObjectName("pll2Label")
        self.horizontalLayout_2.addWidget(self.pll2Label)
        self.layoutWidget2 = QtWidgets.QWidget(self.cw)
        self.layoutWidget2.setGeometry(QtCore.QRect(230, 290, 138, 25))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.readPllPushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.readPllPushButton.setEnabled(True)
        self.readPllPushButton.setMaximumSize(QtCore.QSize(65, 16777215))
        self.readPllPushButton.setObjectName("readPllPushButton")
        self.horizontalLayout_3.addWidget(self.readPllPushButton)
        self.clearPllPushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.clearPllPushButton.setEnabled(True)
        self.clearPllPushButton.setMaximumSize(QtCore.QSize(65, 16777215))
        self.clearPllPushButton.setObjectName("clearPllPushButton")
        self.horizontalLayout_3.addWidget(self.clearPllPushButton)
        self.widget2 = QtWidgets.QWidget(self.cw)
        self.widget2.setGeometry(QtCore.QRect(390, 250, 105, 54))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.resetPushButton = QtWidgets.QPushButton(self.widget2)
        self.resetPushButton.setEnabled(True)
        self.resetPushButton.setObjectName("resetPushButton")
        self.verticalLayout_3.addWidget(self.resetPushButton)
        self.recPushButton = QtWidgets.QPushButton(self.widget2)
        self.recPushButton.setObjectName("recPushButton")
        self.verticalLayout_3.addWidget(self.recPushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JESD_8SYNCV01"))
        self.clearLogPushButton.setText(_translate("MainWindow", "Очистить лог"))
        self.autoStatCheckBox.setText(_translate("MainWindow", "Автообновление статуса"))
        self.label_3.setText(_translate("MainWindow", "Путь к файлу:"))
        self.selectFilePushButton.setText(_translate("MainWindow", "..."))
        self.writeFilePushButton.setText(_translate("MainWindow", "Запись!"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Запись файла"))
        self.label.setText(_translate("MainWindow", "Адрес регистра:"))
        self.label_2.setText(_translate("MainWindow", "Значение регистра:"))
        self.label_4.setText(_translate("MainWindow", "HEX"))
        self.label_5.setText(_translate("MainWindow", "HEX"))
        self.regReadPushButton.setText(_translate("MainWindow", "Считать"))
        self.regWritePushButton.setText(_translate("MainWindow", "Записать"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "Ручная запись"))
        self.label_7.setText(_translate("MainWindow", "PLL1 Status:"))
        self.pll1Label.setText(_translate("MainWindow", "-"))
        self.label_8.setText(_translate("MainWindow", "PLL2 Status:"))
        self.pll2Label.setText(_translate("MainWindow", "-"))
        self.readPllPushButton.setText(_translate("MainWindow", "Проверить"))
        self.clearPllPushButton.setText(_translate("MainWindow", "Очистить"))
        self.resetPushButton.setText(_translate("MainWindow", "Сброс LMK"))
        self.recPushButton.setText(_translate("MainWindow", "Переподключение"))


